### ISSUE TITLE
Error: Uncaught Exception: TypeError: Cannot read properties of null (reading 'setContextMenu') at setTrayMenu

### ISSUE THREAD

**Issue by alinasrabadi** [staniel359/muffon#30]
- Version: 0.1.0-alpha.16 (0.1.0-alpha.16)
- Target: MacOs 12.0.1

Error when running pkg version

`Uncaught Exception:
TypeError: Cannot read properties of null (reading 'setContextMenu')
at setTrayMenu (/Applications/muffon.app/Contents/Resources/app.asar/electron.js:180:8)
at show (/Applications/muffon.app/Contents/Resources/app.asar/electron.js:98:3)
at BrowserWindow.handleReadyToShow (/Applications/muffon.app/Contents/Resources/app.asar/electron.js:129:5)
at BrowserWindow.emit (node:events:394:28)
at node:electron/js2c/browser_init:161:12770
at processTicksAndRejections (node:internal/process/task_queues:78:11)`

**Comment by staniel359** [comment]
@alinasrabadi Please download 0.1.0-beta.
